# Generated by Django 5.2.4 on 2025-07-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cover_headphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/default-image.webp', upload_to=''),
        ),
    ]
