# Generated by Django 5.2.4 on 2025-07-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/default-image.webp', upload_to='images/'),
        ),
    ]
