# Generated by Django 5.2.4 on 2025-07-13 18:16

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/default-image.webp', storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='products/'),
        ),
    ]
