# Generated by Django 5.2.4 on 2025-07-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('₴', 'uah'), ('$', 'usd')], default='₴'),
        ),
    ]
