# Generated by Django 5.2.4 on 2025-07-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_cartitem_cart_cartitem_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_type',
            field=models.CharField(default='', max_length=16),
        ),
    ]
